version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout

      # Set up dependencies
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install Flask pytest prometheus-client requests
#            pip install -r requirements.txt

#      - run:
#          name: Run tests
#          command: |
#            pytest


      # Build the Docker image
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build Docker image
          command: |
            docker build -t my-flask-app .

      # Push the Docker image to Docker Hub
#      - run:
#          name: Push Docker image
#          command: |
#            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
#            docker tag my-flask-app $DOCKER_USERNAME/my-flask-app
#            docker push $DOCKER_USERNAME/my-flask-app

workflows:
  version: 2
  build-and-push:
    jobs:
      - build

